version: '3.8'

services:
  billing-mysql:
    image: billing-mysql
    container_name: billing-mysql-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - dbsql
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/group2?useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root
  dbsql:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: group2
    ports:
      - "3302:3306"
    volumes:
      - C:\Users\Collins\Desktop\db:/var/run/mysqld





